@startuml Configuration State Machine

' left to right direction

[*] --> ResourceStart : ResourceToken

ResourceStart --> ResourceName : LiteralToken

ResourceName --> MappedBy : MappedbyToken

MappedBy --> ModelIdentification : LiteralToken, Contanto que exista\num modelo com esse nome

ModelIdentification -> ItemIteration : StopToken, na presença de ","

ItemIteration --> Propriedade : LiteralToken, Contanto que exista\nno modelo escolhido\nessa propriedade

Propriedade --> ItemIteration : StopToken, na presença de ","

Propriedade -> [*]

@enduml
